version: '3.9'

services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - 9999:8080
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env


#  db_log:
#    container_name: postgres_log
#    image: postgres:15
#    restart: always
#    ports:
#      - 5434:5432
#    environment:
#      POSTGRES_DB: webrise-test-task-db-log
#      POSTGRES_USERNAME: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - pgdata_log:/var/lib/postgresql/data

volumes:
  pgdata:
#  pgdata_log:
