version: '3.9'

services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - 5555:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/webrise-test-task-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: webrise-test-task-db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data


#  db_log:
#    container_name: postgres_log
#    image: postgres:15
#    restart: always
#    ports:
#      - 5434:5432
#    environment:
#      POSTGRES_DB: webrise-test-task-db-log
#      POSTGRES_USERNAME: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - pgdata_log:/var/lib/postgresql/data

volumes:
  pgdata:
#  pgdata_log:
