server:
  port: 8080

spring:
  application:
    name: WEBRise-test-task
  datasource:
    url: jdbc:postgresql://localhost:5433/webrise-test-task-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true