server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    database:
    hibernate:
      ddl-auto: ${DDL_CONTRACT}
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
